### Reshaping Array using Reshape Method
- Reshape array of size (m,n) to (m1,m2.n1), so that m1 x m2 x n1 = m x n



In [5]:
import numpy as np
# Reshaping 3X4 array to 2X2X3 array
arr = np.array([[1, 2, 3, 4],
                [5, 2, 4, 2],
                [1, 2, 0, 1]])
newarr = arr.reshape(2, 2, 3)
print ("Original array:\n", arr)
print("------------")
print("Reshaped array:/n", newarr)

Original array:
 [[1 2 3 4]
 [5 2 4 2]
 [1 2 0 1]]
------------
Reshaped array:/n [[[1 2 3]
  [4 5 2]]

 [[4 2 1]
  [2 0 1]]]


### Flatten Array
- Flatten method flattens array to one dimension and returns copy of collapsed array


In [3]:
# Flatten array
arr = np.array ([[1, 2, 3], [4, 5, 6]])
flat_arr = arr.flatten()
print ("Original array: \n", arr)
print ("Fattened array: \n", flat_arr)

Original array: 
 [[1 2 3]
 [4 5 6]]
Fattened array: 
 [1 2 3 4 5 6]


### NumPy Array Indexing and Slicing
#### Basic Indexing
- Indexing allows us to access the individual elements or subsets of data.


In [ ]:
# 1D Array Indexing
arr = np.array([1,2,3,4,5,6])
print(arr. shape)
print(arr[0]) # first element 
print(arr[-1]) # last element 
print(arr[3]) # fourth Element

#3D Array Indexing
num_2d_array = np.array([
                        [1,2,3],
                        [4,5,6],
                        [6,7,8]
                        ])
print("print dimension of array")
print(num_2d_array.ndim) # print dimension of array
print ("print shape of the array")
print (num_2d_array.shape) # print shape of the array
print("print total number of items")
print(num_2d_array.size) # print total number of items

print("first row first element")
print (num_2d_array [0,0]) # first now first element →>1
print("last row last element")
print(num_2d_array[-1, -1])
print("second row third")
print (num_2d_array [1,2])
print("third row second")
print (num_2d_array [2,1])

#3D Array





(6,)
1
6
4
print dimension of array
2
print shape of the array
(3, 3)
print total number of items
9
first row first element
1
last row last element
8
second row third
6
third row second
7


### Slicing in NumPy
- In NumPy we can access the portion of an array using the slice operator
### 1-D Array Slicing
Syntax: array[start:stop:step]
- start: Index of the first element to be includede in slice 
- stop : index to the last (exclusive)
- step: step size bet each element in the slice

In [10]:
arr = np.array([1,2,3,4,5,6,7,8,9,10,11])
# slice array from index 2-6 (6 exclusive)
print(arr[2:6]) # [3,4,5,6]
# slice array from 0 to 8 with a step size of 2
print (arr [0:8:2]) # [1,3,5,7]
# slice array from index 4 to last element
print (arr [4:])
# slice array from start
print (arr[:5])
#negatice index
print(arr[:2])

arr[:5] =100
print(arr)

[3 4 5 6]
[1 3 5 7]
[ 5  6  7  8  9 10 11]
[1 2 3 4 5]
[1 2]
[100 100 100 100 100   6   7   8   9  10  11]


### 2-D Array Slicing

- syntax: array[row_start:row_step, col_Start:col_stop:col_step]



In [11]:
array_2d = np.array([
    [1,2,3],
    [4,5,6],
    [7,8,9]
])
print(array_2d.ndim)
#slice first row
print(array_2d[0:1])
#slice array from first two rows and first two columns
print(array_2d[0:2,0:2])

2
[[1 2 3]]
[[1 2]
 [4 5]]


### Boolean Array Indexing
- Boolean array indexing allows us to select elements from an array based on conditions. This technique is helpful when we need to filter elements based on certain condition

In [13]:
# Creating an array
arr = np.array([5, 10, 15, 20, 25, 30])
# Select elements greater than 15
print(arr[arr > 15]) # Output: [20 25 30]
# Select elements that are even
print (arr[arr % 2 == 0])
# Modifying elements that satisty a conation
arr[arr>15]=99
print(arr)

# Boolean indexing on a 2-dimensional array
arr2d = np.array([[1, 2, 3], [4, 5, 6], [7, 8, 9]])
# Extract elements greater than 4
print(arr2d[arr2d > 4])
# Output: [5 6 7 8 9]
# Setting elements greater than 4 to zero
arr2d[arr2d > 4] = 0
print(arr2d)

[20 25 30]
[10 20 30]
[ 5 10 15 99 99 99]
[5 6 7 8 9]
[[1 2 3]
 [4 0 0]
 [0 0 0]]


### NumPy Arithmetic Array Operations
- NumPy Array Functions
- NumPy Comparison/Logical Opérations
- NumPy Math Functions
- NumPy Constants
- NumPy Statistical Functions

### NumPy Arithmetic Array Operations
- add()
- subtract()
- multiply()
- divide()
- power()
- mod()

In [17]:
import numpy as np

first_array = np.array([1, 3, 5, 7])
second_array = np.array([2, 4, 6, 8])

# Addition
add_result = np.add(first_array, second_array)
print("Addition:", add_result)

# Subtraction
sub_result = np.subtract(first_array, second_array)
print("Subtraction:", sub_result)

# Multiplication
multi_result = np.multiply(first_array, second_array)
print("Multiplication:", multi_result)

# Power (first_array raised to the power of second_array)
power_result = np.power(first_array, second_array)
print("Power:", power_result)

# Division
div_result = np.divide(first_array, second_array)
print("Division:", div_result)

# Modulus
mod_result = np.mod(first_array, second_array)
print("Modulus:", mod_result)

Addition: [ 3  7 11 15]
Subtraction: [-1 -1 -1 -1]
Multiplication: [ 2 12 30 56]
Power: [      1      81   15625 5764801]
Division: [0.5        0.75       0.83333333 0.875     ]
Modulus: [1 3 5 7]


In [ ]:
import numpy as np

first_array = np.array([1, 3, 5, 7])
second_array = np.array([2])

multi_result = np.multiply(first_array, second_array)
print("Multiplication:", multi_result)

Multiplication: [ 2  6 10 14]


## Numpy Array Function

NumPy has various built-in functions for various purposes
- Array Creation Functions: p.array(), np.zeros (), p.ones (), np.empty () etc
- Manipulation Functions: np.reshape(), np.transpose()
- Mathematical Functions: np.add(), np.subtract(), np.sart(), np.power ()
- Statistical Functions: np.median(), np.mean(), np.std(), np.var ()

In [19]:
data = np.array([1,3,4,57,4,3])
np.mean(data)
np.median(data)
np.std(data)
np.var(data)

406.0

#### Array Manupulation

In [ ]:

numbers = np.array ([1, 2,3,4, 5,6, 7,8, 9])
# reshape the 1D array into a 2D array
reshaped_array = np.reshape(numbers, (3, 3))
# 3 x 3 = 9
print (reshaped_array)
# transpose the 2D array
transposed_array = np.transpose(reshaped_array)
print(transposed_array)

[[1 2 3]
 [4 5 6]
 [7 8 9]]
[[1 4 7]
 [2 5 8]
 [3 6 9]]


### Numpy MAtrix Operations
- Matrix Multiplication np-matmul()
- Dot Product np.dot()
- Cross Product np.cross()
- Transpose np.transpose
- Inverse np.linalg. inverse()
- Determinant linalg. det () linalg=> Linear Algebra
- Norm np.linalg.norm()
- Trace np.linalg. trace()

In [24]:
import numpy as np

# Define the first 3x3 matrix
matrix_1 = np.array([[3, 6, 5],
                     [4, 5, 2],
                     [5, 4, 8]])

# Define the second 3x3 matrix
matrix_2 = np.array([[1, 2, 3],
                     [4, 5, 6],
                     [7, 8, 9]])

# Perform element-wise multiplication
result = matrix_1 * matrix_2

print("Result of element-wise multiplication:")
print(result)

Result of element-wise multiplication:
[[ 3 12 15]
 [16 25 12]
 [35 32 72]]
